expand_imgs:
- gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:95f71a2568ced67ec370b5360f88bec3280601908cac9e62dfbb801114480437
images: []
images_cache: []
install_file_cache: []
install_files:
- target_registry: ccr.ccs.tencentyun.com/zhifou-devops/
  url: https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.37.0/release.yaml
namespace: dev
prefixs:
- gcr.io/
