expand_imgs:
- gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:95f71a2568ced67ec370b5360f88bec3280601908cac9e62dfbb801114480437
images:
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/controller:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/kubeconfigwriter:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/git-init:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/entrypoint:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/nop:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/imagedigestexporter:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/pullrequest-init:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/workingdirinit:v0.37.0
- s_image: gcr.io/google.com/cloudsdktool/cloud-sdk
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/cloud-sdk
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/webhook:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/dashboard
- s_image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.20.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/controller:v0.20.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.20.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/eventlistenersink:v0.20.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.20.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/webhook:v0.20.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.20.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/interceptors:v0.20.0
- s_image: gcr.io/k8s-staging-gateway-api/admission-server:v0.4.3
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/admission-server:v0.4.3
images_cache:
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/controller:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/kubeconfigwriter:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/git-init:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/entrypoint:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/nop:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/imagedigestexporter:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/pullrequest-init:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/workingdirinit:v0.37.0
- s_image: gcr.io/google.com/cloudsdktool/cloud-sdk
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/cloud-sdk
- s_image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.37.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/webhook:v0.37.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/dashboard
- s_image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.20.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/controller:v0.20.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.20.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/eventlistenersink:v0.20.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.20.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/webhook:v0.20.0
- s_image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.20.0
  t_image: ccr.ccs.tencentyun.com/zhifou-devops/interceptors:v0.20.0
install_file_cache:
- https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.37.0/release.yaml
- https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
- https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
- https://raw.githubusercontent.com/projectcontour/contour/release-1.21/examples/render/contour-gateway-provisioner.yaml
- https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
install_files:
- target_registry: ccr.ccs.tencentyun.com/zhifou-devops/
  url: https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
- target_registry: ccr.ccs.tencentyun.com/zhifou-devops/
  url: https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
- target_registry: ccr.ccs.tencentyun.com/zhifou-devops/
  url: https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
- target_registry: ccr.ccs.tencentyun.com/zhifou-devops/
  url: https://raw.githubusercontent.com/projectcontour/contour/release-1.21/examples/render/contour-gateway-provisioner.yaml
namespace: dev
prefixs:
- gcr.io/
- k8s.gcr.io/
