# This is a basic workflow to help you get started with Actions

name: Sync Images

on:
  push:
    paths:
      - '.github/workflows/sync_images.yaml'
      - 'diff_images.json'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        pip3 install yaml2object
        set -ex
        python3 sync_images.py ${{ secrets.DOCKER_USER}} ${{ secrets.DOCKER_PASSWD}} ccr.ccs.tencentyun.com
    - name: Write last result to env
      run: |-
        set -ex
        if [ "`git diff config.yaml|wc -l`" != "0" ]; then
          echo "did_write=true" >> $GITHUB_ENV
        fi

    - uses: EndBug/add-and-commit@v7
      if: ${{ env.did_write == 'true' }}
      with:
        message: "[Scheduled] Refresh config.yaml"
        default_author: github_actions
        push: true
