# This is a basic workflow to help you get started with Actions

name: Get Tekton Images

on:
  push:
    paths:
      - 'tekton_images.yaml'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        pip3 install yaml2object
        python3 sync_images.py ${{ secrets.DOCKER_USER}} ${{ secrets.DOCKER_PASSWD}} ccr.ccs.tencentyun.com

    - uses: EndBug/add-and-commit@v7
      if: ${{ env.did_write == 'true' }}
      with:
        message: "[Scheduled] Refresh config.yaml"
        default_author: github_actions
        push: true
